name: CourseEnrollment
form: $/martinimultimedia/asso/models/courseenrollment/fields.yaml
modelClass: MartiniMultimedia\Asso\Models\CourseEnrollment
defaultRedirect: martinimultimedia/asso/courseenrollments
create:
    redirect: 'martinimultimedia/asso/courseenrollments/update/:id'
    redirectClose: martinimultimedia/asso/courseenrollments
update:
    redirect: martinimultimedia/asso/courseenrollments
    redirectClose: martinimultimedia/asso/courseenrollments
