list: $/martinimultimedia/asso/models/courseenrollment/columns.yaml
modelClass: MartiniMultimedia\Asso\Models\CourseEnrollments
title: CourseEnrollment
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/asso/courseenrollment/update/:id'