list: $/martinimultimedia/asso/models/training/columns.yaml
modelClass: MartiniMultimedia\Asso\Models\Training
title: Trainings
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/asso/trainings/update/:id'
