list: $/martinimultimedia/asso/models/trainingenrollment/columns.yaml
modelClass: MartiniMultimedia\Asso\Models\TrainingEnrollments
title: Presenze
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/asso/trainingenrollment/update/:id'