name: People
modelClass: MartiniMultimedia\Asso\Models\Person
form: $/martinimultimedia/asso/models/person/fields.yaml
defaultRedirect: martinimultimedia/asso/people
create:
    redirect: 'martinimultimedia/asso/people/update/:id'
    redirectClose: martinimultimedia/asso/people
update:
    redirect: martinimultimedia/asso/people
    redirectClose: martinimultimedia/asso/people
preview: {  }
