list: $/martinimultimedia/asso/models/company/columns.yaml
modelClass: MartiniMultimedia\Asso\Models\Company
title: Aziende
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/asso/companies/update/:id'
