list: $/martinimultimedia/asso/models/venue/columns.yaml
modelClass: MartiniMultimedia\Asso\Models\Venue
title: Aule
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
defaultSort:
    column: name
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/asso/venues/update/:id'
